edition = "2024"
style_edition = "2024"
unstable_features = true

comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Module"
wrap_comments = true
group_imports = "StdExternalCrate"
