[workspace]
members = [
  "crates/cli",
  "crates/common",
  "crates/graph",
  "crates/macros",
  "crates/master",
  "crates/task",
  "crates/worker",
]
resolver = "3"
exclude = ["tasks/*", "pipelines/*"]

[workspace.dependencies]
anyhow = "1"
futures = "0.3"
kanal = { version = "0.1", features = ["async"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.45", features = ["full"] }
