[workspace]
members = [
  "crates/cli",
  "crates/core",
  "crates/engine",
  "crates/flow",
  "crates/macros",
  "crates/master",
  "crates/worker",

  "examples/simple/simple",
  "examples/simple/tasks/add",
  "examples/simple/tasks/is_less",
]
resolver = "3"
exclude = ["tasks/*", "pipelines/*"]

[workspace.dependencies]
anyhow = "1"
erased-serde = "0.4"
futures = "0.3"
kanal = { version = "0.1", features = ["async"] }
itertools = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.45", features = ["full"] }
inventory = "0.3"
darling = "0.20"

[package]
name = "namu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
namu-core = { path = "crates/core" }
namu-engine = { path = "crates/engine" }
namu-flow = { path = "crates/flow" }
namu-macros = { path = "crates/macros" }
inventory = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
itertools = { workspace = true }
