[workspace]
members = [
  "crates/cli",
  "crates/graph",
  "crates/macros",
  "crates/master",
  "crates/task",
  "crates/worker",
]
resolver = "3"
exclude = ["tasks/*", "pipelines/*"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }