include = ["**/*.toml"]

[formatting]

[[rule]]

[rule.formatting]
include = ["taplo.toml"]
keys = ["exclude"]

array_auto_collapse = false

[[rule]]

[rule.formatting]
include = ["**/Cargo.toml"]

array_auto_expand = false
inline_table_expand = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "dependencies",
    "*-dependencies",
    "workspace",
    "workspace.members",
    "workspace.exclude",
]

[rule.formatting]
reorder_keys = true
align_comments = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["package", "workspace.package"]

[rule.formatting]
reorder_keys = false
align_comments = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["features"]

[rule.formatting]
reorder_arrays = true
