[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8"
proc-macro2 = "1"
proc-macro-error = { version = "1", default-features = false }
quote = "1"
syn = { version = "2", features = [
    "full",
    "visit-mut",
    "visit",
    "extra-traits",
] }
darling = "0.20.11"

[dev-dependencies]
macrotest = "1.1.0"
anyhow = "1"
