[package]
name = "namu-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
namu-core = { path = "../core" }
scc = "2.3"
kanal = { workspace = true }
itertools = { workspace = true }
erased-serde = { workspace = true }
anyhow = { workspace = true }
